language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export GIT_REPO=https://$REPO_TOKEN@github.com/sjfkai/mapLocation.git
- export CODING_REPO=https://$CODING_TOKEN@e.coding.net/sjfkai/mapLocation.git
install:
- yarn
script:
- yarn run publish
notifications:
  email:
    recipients:
      - sjfkai@163.com
    on_success: never
    on_failure: always
