language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export GIT_REPO=https://blog.aidengrong.top
- export CODING_REPO=https://map.aidengrong.top
install:
- yarn
script:
- yarn run publish
notifications:
  email:
    recipients:
      - aidengrong@aidengrong.top
    on_success: never
    on_failure: always
